<template>
  <div>
    <slot />
    <Translation
      :class="$style.translation"
      :data="props.answer"
      :show="visible"
      :language="language"
      :format-en-markdown="formatEnMarkdown"
      @close-translation="changeShowTranslation"
    />
  </div>
</template>
<script setup lang="ts">
import Translation from "@/client/views/intelligentQA/components/Translation.vue";
import { formatReference } from "@/client/views/intelligentQA/utils";

const props = defineProps<{
  answer: string | undefined;
  reference?: Record<string, string>[];
}>();

const visible = defineModel<boolean>("visible");
const language = defineModel<string>("language");

const changeShowTranslation = (value: boolean) => {
  visible.value = value;
};

const formatEnMarkdown = (data: string) => {
  let result = data.replace(/\b\d+./g, ".");
  const advertising = "\n\nThe above answers were generated by Transwarp Infinity https://wuya-ai.com";
  const reference = formatReference(props?.reference || []);
  result = result + `\n\n Citations:\n${reference}` + advertising;
  return result;
};
</script>

<style module lang="scss">
.translation {
  margin-top: 20px;
  border-top: 1px solid #e0e1e5;
}
</style>
